enum Breed:
  case Siamese
  case Persian
  case MaineCoon
  case Ragdoll
  case Bengal
  case Abyssinian
  case Birman
  case OrientalShorthair
  case Sphynx
  case DevonRex
  case ScottishFold
  case Metis